site_name: "customer-api-elghazali"
site_description: "A service that calls a backend customer service using Flogo - developped by Hicham"

nav:
  - Introduction: README.md

plugins:
  - techdocs-core